version: '3'

services:
  postgres:
    image: 'postgres:15.2'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=ArsenyRevunov52'
      - 'POSTGRES_PASSWORD=ArsenyRevunov52'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=Wallet-Service'